# random sampling 

In [1]:
import  numpy as np
import random 

In [3]:
np.random.random() # this function gives value beetween 1 to 0

0.03546834140244326

In [4]:
np.random.random((3,3))

array([[0.96481315, 0.86841821, 0.70547471],
       [0.41860085, 0.35897159, 0.19594979],
       [0.15270321, 0.47316684, 0.84732928]])

# randint(low, high=None, size=None, dtype='l')

In [6]:
np.random.randint(1,4)

1

In [10]:
np.random.randint(1,4,(4,4))

array([[2, 3, 2, 1],
       [1, 2, 3, 3],
       [2, 2, 1, 3],
       [1, 2, 3, 3]])

In [11]:
np.random.randint(1,4,(2,4,4))

array([[[2, 1, 3, 3],
        [1, 3, 3, 2],
        [1, 2, 2, 1],
        [3, 3, 1, 1]],

       [[1, 3, 2, 1],
        [1, 2, 1, 3],
        [2, 1, 3, 3],
        [2, 3, 3, 2]]])

In [13]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [14]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [15]:
2**32 -1

4294967295

In [19]:
np.random.rand(4)     # it returnns n-d array   only positive value 0 to 1

array([0.76545582, 0.01178803, 0.61194334, 0.33188226])

In [22]:
np.random.randn(4)   # it returnns n-d array include positive and negtive both 0 to 1

array([ 0.38936304, -0.52699615, -0.51430791,  0.89760917])

In [25]:
x = [1,2,3,4]
np.random.choice(x)

1

In [27]:
x = [1,2,3,4]
for i in range(0,10):
    print(np.random.choice(x))

2
3
3
4
1
1
1
1
3
3


In [29]:
np.random.choice(6, 3)

array([0, 2, 5])

In [30]:
np.random.choice(6, 10)

array([1, 3, 1, 2, 5, 0, 1, 1, 5, 0])

In [38]:
 np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 2, 3], dtype=int64)

In [41]:
np.random.permutation([1,2,3,4])

array([3, 2, 1, 4])

In [42]:
np.random.permutation([1,2,3,4])

array([1, 3, 4, 2])

In [43]:
 np.random.permutation(10)

array([4, 2, 0, 7, 9, 8, 5, 6, 3, 1])

In [44]:
 np.random.permutation(10)

array([4, 1, 0, 7, 2, 6, 3, 9, 8, 5])

In [45]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])