# string operation  compression and information

In [1]:
import numpy as np

In [2]:
str1 = "hello saurabh "
str2 = "how are you"

In [9]:
# Return element-wise string concatenation for two arrays of str or unicode.
print(np.char.add(str1,str2))

hello saurabh how are you


In [11]:
# Return an array with the elements converted to uppercase.
print(np.char.upper(str1)  )

HELLO SAURABH 


In [12]:
np.char.upper(str1)

array('HELLO SAURABH ', dtype='<U14')

In [14]:
# Return a copy of `a` with only the first character of each element
print(np.char.capitalize(str1))

Hello saurabh 


In [16]:
print(np.char.asbytes(str1))   # isko samjha do sir

b'hello saurabh '


In [18]:
np.char.bool_("")

False

In [19]:
np.char.bool_("str1")

True

In [29]:
print(np.char.center("hello saurabh",60,fillchar='*'))

***********************hello saurabh************************


In [31]:
np.char.character(str1)  # isko bhi samjha do

TypeError: cannot create 'numpy.character' instances

# np.char.endswith(a, suffix, start=0, end=None)

In [32]:
s = np.array(['foo', 'bar'])
np.char.endswith(s,'ar')

array([False,  True])

In [38]:
np.char.endswith("saurabh barasiya" ,'ar',start = 5,end = 10)

array(False)

In [44]:
np.char.endswith("syaurabh barasi" ,'ya',start = 0,end =3 )

array(True)

In [49]:
np.char.endswith("saurabh barasiya" ,'ya',start = 5,end = 20)

array(True)

# np.char.startswith(a, prefix, start=0, end=None)

In [50]:
# Returns a boolean array which is `True` where the string element
# in `array` starts with `prefix`, otherwise `False`.
s = ['hello','hy']
np.char.startswith(s,'h')

array([ True,  True])

In [51]:
np.char.lower("SAURABH")

array('saurabh', dtype='<U7')

In [52]:
np.char.lower("Saurabh")

array('saurabh', dtype='<U7')

In [55]:
np.char.title("saurabh")   # frist character ko capitel kar deta h 

array('Saurabh', dtype='<U7')

In [56]:
sc = ['hy', 'my','name','is','saurabh']
np.char.title(sc)

array(['Hy', 'My', 'Name', 'Is', 'Saurabh'], dtype='<U7')

In [57]:
s = "my name is saurabh"
np.char.split(s)

array(list(['my', 'name', 'is', 'saurabh']), dtype=object)

In [58]:
s = "my name is saurabh"
print(np.char.split(s))

['my', 'name', 'is', 'saurabh']


In [60]:
s = "my name is saurabh"
print(type(np.char.split(s)))

<class 'numpy.ndarray'>


In [61]:
np.char.splitlines("hello \n saurabh ")

array(list(['hello ', ' saurabh ']), dtype=object)

# np.char.count(a, sub, start=0, end=None)

In [62]:
np.char.count('saurabh barasiya','a')

array(5)

In [ ]:
np.char.count('saurabh barasiya','a',)

# np.char.equal(x1, x2)

In [65]:
np.char.equal("sau",'sau')

array(True)

In [66]:
np.char.equal('saurabh','barasiya')

array(False)

In [69]:
np.char.equal(['saurabh','barassiyaa'],['saurabh','barassiya'])

array([ True, False])

In [70]:
np.char.compare_chararrays()    # isko samjha do sir

TypeError: compare_chararrays() missing required argument 'a1' (pos 1)

# np.char.join(sep, seq)

In [73]:
np.char.join('@','saurabh')

array('s@a@u@r@a@b@h', dtype='<U13')

In [74]:
np.char.join(["@","*"],['saurabh','barasiya'])

array(['s@a@u@r@a@b@h', 'b*a*r*a*s*i*y*a'], dtype='<U15')

# np.char.replace(a, old, new, count=None)

In [77]:
a = ["saurabh","barasiya",'aman','rohan']
np.char.replace(a ,"barasiya","ronit")

array(['saurabh', 'ronit', 'aman', 'rohan'], dtype='<U7')

In [79]:
a = ["saurabh","barasiya",'aman','rohan']
np.char.replace(a ,"barasiya","ronit")

array(['saurabh', 'ronit', 'aman', 'rohan'], dtype='<U7')

# np.char.decode(a, encoding=None, errors=None)

In [94]:
a = np.array(['sa'])
np.char.encode(a, encoding='cp037')    # ye code bhi samaj me nahi aa raha h sir

array([b'\xa2\x81'], dtype='|S2')

In [95]:
# [b'\xa2\x81']
np.char.decode([b'\xa2\x81'], encoding='cp037') 

array(['sa'], dtype='<U2')

# np.char.find(a, sub, start=0, end=None)`

In [11]:
arr = np.array(['saurabh','barasiya','ronit','raj'])
np.char.find(arr,'j')

array([-1, -1, -1,  2])

In [5]:
np.char.find("saurabh",'a')

array(1)

In [4]:
s = np.array(['saurabh '])
s1 = np.array(['barasiya '])
print(np.char.add(s,s1))

['saurabh barasiya ']
