# about matrix

In [2]:
import numpy as np

In [4]:
mx1 = np.array([[1,1,1],[1,1,1],[1,1,1]])
mx1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
mx1.ndim

2

#   np.ones(shape, dtype=None, order='C')

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
np.ones((3,3),dtype = np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [17]:
mx_1s = np.ones((3,3),dtype = np.int32)
mx_1s

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
mx_1s.ndim

2

In [19]:
mx_1s.dtype

dtype('int32')

# np.zeros(shape, dtype=float, order='C')

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
 np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [23]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [24]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.zeros((3,3),dtype = bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [27]:
# 0 represent false and 1 represent true

In [28]:
np.zeros((3,3),dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [30]:
# when 0  and false is converted into string so we got (empty string)
em_str = ''
print(bool(em_str))

False


# create empty matrix

### np.empty(shape, dtype=float, order='C')

In [31]:
np.empty()

TypeError: empty() missing required argument 'shape' (pos 1)

In [32]:
np.empty([2, 2])

array([[0., 0.],
       [0., 0.]])

In [33]:
np.empty([2, 2], dtype=int)

array([[0, 0],
       [0, 0]])