# numpy function

In [1]:
import numpy as np

## arange([start,] stop[, step,], dtype=None)

In [2]:
ar_1d = np.arange(1,12)

In [3]:
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [4]:
ar_1d = np.arange(0,13,2)
print(ar_1d)

[ 0  2  4  6  8 10 12]


In [5]:
ar_1d = np.arange(0,13,2,dtype = np.float)
print(ar_1d)

[ 0.  2.  4.  6.  8. 10. 12.]


# linespace()

# # np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [6]:
np.linspace()


TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'

In [8]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [9]:
'''
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
'''
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [10]:
a = np.linspace(2.0, 3.0, num=5, retstep=True) #retstep : bool, optionalIf True, return (`samples`, `step`), where `step` is the spacing between samples.
print(a)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


# reshape()

## Gives a new shape to an array without changing its data.

# # np.reshape(a, newshape, order='C')

In [11]:
a = np.zeros((10, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
 b = a.T
 b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
c = b.view()
print(c)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
 a = np.arange(6).reshape((3, 2))
 a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
b = np.reshape(a,(2,3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
#when you convert 1-d array to  3d  so you give 3 value  (frist value represent 3-d ,secound value represent 2-d,third value represent 1-d)
arr5 = np.arange(0,12).reshape(2,3,2)
arr5

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [19]:
arr5.ndim

3

In [20]:
arr5.size

12

In [22]:
arr5.dtype

dtype('int32')

In [23]:
type(arr5)

numpy.ndarray

# ravel()
##   np.ravel(a, order='C')

In [24]:
# this function convert multidimension into 1-d array
arr6 = np.arange(0,12).reshape(2,3,2)
print(arr6)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [25]:
arr6.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
np.ravel(arr6)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# flatten()
## a.flatten(order='C')

In [27]:
# this function also convert multidimension into 1-d array
arr7 = np.arange(0,12).reshape(2,3,2)
print(arr7)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [29]:
arr7.flatten(order = 'C') # 'C' means to flatten in row-major (C-style) order.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
arr7.flatten(order = 'F')  # 'F' means to flatten in column-major (Fortran-style)

array([ 0,  6,  2,  8,  4, 10,  1,  7,  3,  9,  5, 11])

In [33]:
arr8 = np.arange(0,12).reshape(3,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
arr8.flatten(order = 'F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [35]:
arr8.flatten(order = 'A')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
arr8.flatten(order = 'K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# transpose()

In [39]:
# this function convert row into column
arr9 = np.arange(0,12).reshape(2,6)
arr9

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [40]:
arr9.transpose()

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [41]:
arr9.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])