# array conctination and split

In [1]:
import numpy as np

In [12]:
arr1 = np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
arr2 = np.arange(17,33).reshape(4,4)
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

# np.concatenate((a1, a2, ...), axis=0, out=None)

In [14]:
#  when i conctinate both arry so we use 
# The arrays must have the same shape, except in the dimension
# corresponding to `axis` (the first, by default).
print(arr1)
print(arr2)
np.concatenate((arr1,arr2))   

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [15]:
np.concatenate((arr1,arr2),axis = 1)  

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [19]:
arr3 = np.array([1,2,3])

In [20]:
arr3.shape

(3,)

In [21]:
np.concatenate((arr1,arr3))

ValueError: all the input arrays must have same number of dimensions

In [22]:
np.vstack((arr1,arr3))  # sape same hona chahiye

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [23]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [25]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [26]:
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


# np.split(ary, indices_or_sections,axis = 0)

In [49]:
mask=np.split(arr1,4)

In [47]:
print(mask[0])
print(mask[1])
print(mask[2])
print(mask[3])

[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]


In [50]:
mask=np.split(arr1,1)

In [51]:
mask

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [52]:
mask=np.split(arr1,2)

In [53]:
mask[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
mask[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
print(mask[0],mask[1])

[[1 2 3 4]
 [5 6 7 8]] [[ 9 10 11 12]
 [13 14 15 16]]


In [56]:
type(mask)

list

In [57]:
type(mask[0])

numpy.ndarray

In [61]:
arr = [1,2,3,4,5,6]
mask=np.split(arr,[2,4,])

In [64]:
mask

[array([1, 2]), array([3, 4]), array([5, 6])]