# Lecture 1

In [2]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)

numpy.ndarray

In [5]:
# to cheack dimension
arr_1d.ndim  

1

In [7]:
arr_2d =  np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)
    

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
type(arr_2d)

numpy.ndarray

In [9]:
arr_2d.ndim

2

In [10]:
# cheack array size
arr_2d.size

8

In [12]:
arr_1d.size

4

In [14]:
# to cheack sape means rows and column    (row, column)
arr_2d.shape

(2, 4)

In [15]:
arr_1d.shape

(4,)

In [16]:
# to cheack datatype
arr_2d.dtype

dtype('int32')

In [17]:
arr_1d.dtype

dtype('int32')

# harshit sir

In [20]:
num = [1,2,3]
arr = np.array(num)
arr

array([1, 2, 3])

In [21]:
arr.ndim

1

#  1-d array = vector
#  2-d array = matrix
#  n-d array = tensor

In [22]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [23]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [24]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [25]:
new = np.array(np.mat('1 2; 3 4'))

In [26]:
new

array([[1, 2],
       [3, 4]])

In [29]:
new1 = np.array(np.mat('1 2; 3 4;5 6'))
new1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
new2 = np.array(np.mat('1'))    # it gives always matrix  not vector
new2

array([[1]])

In [34]:
new2.ndim

2

In [35]:
new2.shape

(1, 1)

In [36]:
new2.dtype

dtype('int32')

In [3]:
new3 = np.array(np.mat('1',dtype=float))    # it gives always matrix  not vector
new3

array([[1.]])

In [4]:
new3.dtype

dtype('float64')