# Mathematic operation using numpy

In [1]:
import numpy as np 

In [4]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# elementry wise addtion
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
# elementry wise subtract
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
# elementry wise divide
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# elementry wise multiplection
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [13]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# perfrom matrix multiplication
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [16]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# finding maximum and minimum value
# np.max(a, axis=None, out=None, keepdims=no value, initial=no value)

In [20]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
np.max(arr1)  #  it gives  maximum value

9

In [23]:
np.max(arr1,axis=0)   # axix 0 means column

array([7, 8, 9])

In [24]:
np.max(arr1,axis=1)  # axis 1 means row

array([3, 6, 9])

In [25]:
np.argmax(arr1)  # gives maximum index value

8

In [26]:
np.argmin(arr1) 

0

In [27]:
# np.argmin(arr1,axis =0) 

array([0, 0, 0], dtype=int64)

In [28]:
# np.argmin(arr1,axis =1)

array([0, 0, 0], dtype=int64)

In [29]:
# performm addtion in matrix element
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# np.sum(['a', 'axis=None', 'dtype=None', 'out=None', 'keepdims=no value', 'initial=no value'])

In [32]:
np.sum(arr1)

45

In [33]:
np.sum(arr1,axis=0)  # sum columns wise 

array([12, 15, 18])

In [34]:
np.sum(arr1,axis=1) # sum row wise

array([ 6, 15, 24])

In [35]:
np.mean(arr1)  # gives mean value

5.0

In [36]:
np.sqrt(arr1)  # it gives squre root of every element

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [37]:
np.std(arr1)  # it gives standard division

2.581988897471611

In [38]:
np.exp(arr1)  # it gives exponent of every element  (e**x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [39]:
np.exp(2)

7.38905609893065

In [40]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [41]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])